config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#homepage'
  get 'about', to: 'pages#about'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end
  def about
  end
  
end

app/controllers/posts_controller.rb
 class PostsController <ApplicationController


  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(article_params)
      
      flash[:notice] = "Post was successfully updated"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end
  
  def create
    @post = Post.new(article_params)
    if @post.save
      flash[:notice] = "Post was successfully Created"
      @post.totalcost
      redirect_to post_path(@post)
    else
      render 'new'
    end 
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
    
  end

   




 
  private
    def article_params
      params.require(:post).permit(:Name, :Phone, :Adress, :Veh_Year, :Make, :Model, :LicPlate, :Miles, :VIN, :Visa, :MasterCard, :Discover, :Cash, :Pair, :Air, :Acl, :Tc_cac, :Efe, :Egr, :Can, :Cat, :Mil, :O2s, :Pcv, :Timing, :CASmog, :CAInsp, :VIN2, :CASmogCert, :PreInsp, :ReInsp, :EngCover, :Other, :Evap, :Est, :GasCap, :Mis, :Tax)
    end 

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg|%>
      <ul>
          <li><%= msg %></li>
      </ul>
       
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the AlphaBlog About page</h1>
<%= link_to 'Homepage', root_path%>

app/views/pages/homepage.html.erb
<h1>This is the AlphaBlog Home page</h1>
<%= link_to 'About', about_path %>

app/views/posts/edit.html.erb
<h1> Edit Post</h1>

<%= form_for @post do |f| %>
    <%= f.label :Name %><br>
    <%= f.text_field :Name %><br>
    <%= f.label :Phone %> <br>
    <%= f.text_field :Phone %><br>
    <%= f.label :Adress %> <br>
    <%= f.text_field :Adress %><br>
    <%= f.label(:Veh_Year, "Veh/Year")   %> <br>
    <%= f.text_field :Veh_Year %><br>
    <%= f.label :Make %> <br>
    <%= f.text_field :Make %><br>
    <%= f.label :Model  %> <br>
    <%= f.text_field :Model %><br>
    <%= f.label(:LicPlate, "License Plate") %> <br>
    <%= f.text_field :LicPlate %><br>
    <%= f.label :Miles %> <br>
    <%= f.text_field :Miles %><br>
    <%= f.label(:VIN, "VIN") %> <br>
    <%= f.text_field :VIN %>
  </p>

<h3>Payment Method</h3>
  <p>
  
    <%= f.label :Visa %> 
    <%= f.check_box :Visa%> <br />
    <%= f.label :MasterCard %>
    <%= f.check_box :MasterCard %> <br />
    <%= f.label :Discover %>
    <%= f.check_box :Discover%> <br />
    <%= f.label :Cash %>
    <%= f.check_box :Cash%> <br />
  </p>

<h3>__________</h3>
  <p>
    <%= f.label(:Pair,"PAIR")%> 
    <%= f.check_box :Pair %> <br />
    <%= f.label(:Air,"AIR")%> 
    <%= f.check_box :Air %> <br />
    <%= f.label(:Acl,"ACL")%> 
    <%= f.check_box :Acl%> <br />
    <%= f.label(:Tc_cac,"TC/CAC")%> 
    <%= f.check_box :Tc_cac%> <br />
    <%= f.label(:Efe,"EFE")%> 
    <%= f.check_box :Efe %> <br />
    <%= f.label(:Egr,"EGR")%> 
    <%= f.check_box :Egr%> <br />
    <%= f.label(:Can,"CAN")%> 
    <%= f.check_box :Can%> <br />
    <%= f.label(:Cat,"CAT")%> 
    <%= f.check_box :Cat%> <br />
    <%= f.label(:Mil,"MIL")%> 
    <%= f.check_box :Mil%> <br />
    <%= f.label(:O2s,"O2S")%> 
    <%= f.check_box :O2s%> <br />
    <%= f.label(:Pcv,"PCV")%> 
    <%= f.check_box :Pcv%> <br />
    <%= f.label :Timing%> 
    <%= f.check_box :Timing%> <br />
</p>

<H3>Fees:</H3>
  <p>
   <%= f.label(:CASmog, "California Smog Inspection") %> <br>
    <%= f.text_field :CASmog %><br>
    <%= f.label(:CAInsp, "California Smog Insp./ Heavy Duty Vehicles") %> <br>
    <%= f.text_field :CAInsp %><br>
    <%= f.label(:VIN2, "VIN") %> <br>
    <%= f.text_field :VIN2 %><br>
    <%= f.label(:CASmogCert, "California Smog Certificate") %> <br>
    <%= f.text_field :CASmogCert %><br>
    <%= f.label(:PreInsp, "Pre-Inspection") %> <br>
    <%= f.text_field :PreInsp %><br>
    <%= f.label(:ReInsp, "Re-Inspection") %> <br>
    <%= f.text_field :ReInsp %><br>
    <%= f.label(:EngCover, "Remove Eng. Cover (If Needed) Vans") %> <br>
    <%= f.text_field :EngCover %><br>
    <%= f.label(:Other, "Other") %> <br>
    <%= f.text_field :Other %><br>
    <%= f.label(:Evap, "Evap. Test") %> <br>
    <%= f.text_field :Evap %><br>
    <%= f.label(:Est, "Estimates") %> <br>
    <%= f.text_field :Est %><br>
    <%= f.label(:GasCap, "Gas Cap(s)") %> <br>
    <%= f.text_field :GasCap %><br>
    <%= f.label(:Mis, "Miscellaneous") %> <br>
    <%= f.text_field :Mis %><br>
    <%= f.label(:Tax, "Tax") %> <br>
    <%= f.text_field :Tax %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Listing all Posts</h1>


<table>
  <tr>
      <th>Name</th>
       <th>Phone</th>
  </tr>

  <% @posts.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= post.Name %></td>
    <td><%= post.Phone %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Show', post_path(post) %></td>
  </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1> Make Something</h1>



<%= form_for @post do |f| %>
    <%= f.label :Name %><br>
    <%= f.text_field :Name %><br>
    <%= f.label :Phone %> <br>
    <%= f.text_field :Phone %><br>
    <%= f.label :Adress %> <br>
    <%= f.text_field :Adress %><br>
    <%= f.label(:Veh_Year, "Veh/Year")   %> <br>
    <%= f.text_field :Veh_Year %><br>
    <%= f.label :Make %> <br>
    <%= f.text_field :Make %><br>
    <%= f.label :Model  %> <br>
    <%= f.text_field :Model %><br>
    <%= f.label(:LicPlate, "License Plate") %> <br>
    <%= f.text_field :LicPlate %><br>
    <%= f.label :Miles %> <br>
    <%= f.text_field :Miles %><br>
    <%= f.label(:VIN, "VIN") %> <br>
    <%= f.text_field :VIN %>
  </p>

<h3>Payment Method</h3>
  <p>
  
    <%= f.label :Visa %> 
    <%= f.check_box :Visa%> <br />
    <%= f.label :MasterCard %>
    <%= f.check_box :MasterCard %> <br />
    <%= f.label :Discover %>
    <%= f.check_box :Discover%> <br />
    <%= f.label :Cash %>
    <%= f.check_box :Cash%> <br />
  </p>

<h3>__________</h3>
  <p>
    <%= f.label(:Pair,"PAIR")%> 
    <%= f.check_box :Pair %> <br />
    <%= f.label(:Air,"AIR")%> 
    <%= f.check_box :Air %> <br />
    <%= f.label(:Acl,"ACL")%> 
    <%= f.check_box :Acl%> <br />
    <%= f.label(:Tc_cac,"TC/CAC")%> 
    <%= f.check_box :Tc_cac%> <br />
    <%= f.label(:Efe,"EFE")%> 
    <%= f.check_box :Efe %> <br />
    <%= f.label(:Egr,"EGR")%> 
    <%= f.check_box :Egr%> <br />
    <%= f.label(:Can,"CAN")%> 
    <%= f.check_box :Can%> <br />
    <%= f.label(:Cat,"CAT")%> 
    <%= f.check_box :Cat%> <br />
    <%= f.label(:Mil,"MIL")%> 
    <%= f.check_box :Mil%> <br />
    <%= f.label(:O2s,"O2S")%> 
    <%= f.check_box :O2s%> <br />
    <%= f.label(:Pcv,"PCV")%> 
    <%= f.check_box :Pcv%> <br />
    <%= f.label :Timing%> 
    <%= f.check_box :Timing%> <br />
</p>

<H3>Fees:</H3>
  <p>
    <%= f.label(:CASmog, "California Smog Inspection") %> <br>
    <%= f.text_field :CASmog %><br>
    
    <%= f.label(:CAInsp, "California Smog Insp./ Heavy Duty Vehicles") %> <br>
    <%= f.text_field :CAInsp %><br>
    <%= f.label(:VIN2, "VIN") %> <br>
    <%= f.text_field :VIN2 %><br>
    <%= f.label(:CASmogCert, "California Smog Certificate") %> <br>
    <%= f.text_field :CASmogCert %><br>
    <%= f.label(:PreInsp, "Pre-Inspection") %> <br>
    <%= f.text_field :PreInsp %><br>
    <%= f.label(:ReInsp, "Re-Inspection") %> <br>
    <%= f.text_field :ReInsp %><br>
    <%= f.label(:EngCover, "Remove Eng. Cover (If Needed) Vans") %> <br>
    <%= f.text_field :EngCover %><br>
    <%= f.label(:Other, "Other") %> <br>
    <%= f.text_field :Other %><br>
    <%= f.label(:Evap, "Evap. Test") %> <br>
    <%= f.text_field :Evap %><br>
    <%= f.label(:Est, "Estimates") %> <br>
    <%= f.text_field :Est %><br>
    <%= f.label(:GasCap, "Gas Cap(s)") %> <br>
    <%= f.text_field :GasCap %><br>
    <%= f.label(:Mis, "Miscellaneous") %> <br>
    <%= f.text_field :Mis %><br>
    <%= f.label(:Tax, "Tax") %> <br>
    <%= f.text_field :Tax %>

   
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1>Showing <%=@post.Name %>'s Post</h1>
<h3>
  Name: <%= @post.Name %> <br>
  Phone: <%= @post.Phone %> <br>
  Address: <%= @post.Adress %> <br>
  Veh/Year: <%= @post.Veh_Year %> <br>
  Make: <%= @post.Make %> <br>
  Model: <%= @post.Model %> <br>
  License Plate: <%= @post.LicPlate %> <br>  
  Miles: <%= @post.Miles %> <br>
  V.I.N.: <%= @post.VIN %> <br>
</h3>

<h2>Payment Method:</h2>

<h4>
    Paid With Visa
    <% if @post.Visa == "1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Visa == "0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %> <br>
    Paid With MasterCard
    <% if @post.MasterCard=="1"%>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.MasterCard == "0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %> <br>
    Paid With Discover
    <% if @post.Discover == "1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %> 
    <% if @post.Discover == "0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %> <br>
    Paid With Cash
    <% if @post.Cash=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Cash == "0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %> <br>
</h4>

<h4>
    PAIR 
    <% if @post.Pair=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Pair=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    AIR
    <% if @post.Air=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Air=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    ACL
    <% if @post.Acl=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Acl=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    TC/CAC
    <% if @post.Tc_cac=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Tc_cac=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    EFE
    <% if @post.Efe=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Efe=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    EGR
    <% if @post.Egr=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Egr=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    CAN
    <% if @post.Can=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Can=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    CAT
    <% if @post.Cat=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Cat=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    MIL
    <% if @post.Mil=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Mil=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    O2S
    <% if @post.O2s=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.O2s=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    PCV
    <% if @post.Pcv=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Pcv=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>

    Timing
    <% if @post.Timing=="1" %>
      <span style="font-family:Wingdings">&#163;</span>
    <% end %>
    <% if @post.Timing=="0" %>
      <span style="font-family:Wingdings">&#161;</span>
    <% end %><br>
</h4>

$ <%=@post.CASmog.to_f.round(2) %> | California Smog Inspection<br>
$ <%=@post.CAInsp.to_f.round(2) %> | California Smog Insp./ Heavy Duty Vehicles<br>
$ <%=@post.VIN2.to_f.round(2) %> | VIN<br>
$ <%=@post.CASmogCert.to_f.round(2) %> | California Smog Certificate<br>
$ <%=@post.PreInsp.to_f.round(2) %> | Pre-Inspection<br>
$ <%=@post.ReInsp.to_f.round(2) %> | Re-Inspection<br>
$ <%=@post.EngCover.to_f.round(2) %> | Remove Eng. Cover (If Needed) Vans<br>
$ <%=@post.Other.to_f.round(2) %> | Other<br>
$ <%=@post.Evap.to_f.round(2) %> | Evap. Test<br>
$ <%=@post.Est.to_f.round(2) %> | Estimates<br>
$ <%=@post.GasCap.to_f.round(2) %> | Gas Cap(s)<br>
$ <%=@post.Mis.to_f.round(2) %> | Miscellaneous<br>
$ <%=@post.Tax.to_f %> | Tax<br>

<div id="divCheckbox" style="display: none;"> 
<%=sum=0 %>
<%=sum+=@post.CASmog.to_f %>
<%=sum+=@post.CAInsp.to_f %>
<%=sum+=@post.VIN2.to_f %>
<%=sum+=@post.CASmogCert.to_f %>
<%=sum+=@post.PreInsp.to_f %>
<%=sum+=@post.ReInsp.to_f %>
<%=sum+=@post.EngCover.to_f %>
<%=sum+=@post.Other.to_f %>
<%=sum+=@post.Evap.to_f %>
<%=sum+=@post.Est.to_f %>
<%=sum+=@post.GasCap.to_f %>
<%=sum+=@post.Mis.to_f %>
<%=tax=sum* @post.Tax.to_f%>

  

</div>
$ <%=sum.round(2)%> | Total Without Tax<br>
$ <%=(tax+sum).round(2)%> | Total With Tax<br>



<%= link_to "Edit this Post", edit_post_path(@post) %> |

<%= link_to "Back to post listing", posts_path %>